export const enum Status {
  NEW = "NOVO",
  NOT_REMOVED = "NÃO SERÁ REMOVIDO",
  DUPLICATE = "DUPLICADO",
  NOT_ERROR = "NÃO É ERRO",
  SOLVED = "RESOLVIDO",
  APPROVED = "APROVADO",
  DISAPPROVED = "REPROVADO",
}
