import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
} from "@mui/material";
import { Container } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import TableHeadEnhanced from "../src/components/TableHeadEnhanced";
import { Priority } from "../src/enums/priority.enum";
import { Status } from "../src/enums/status.enum";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  interface Issue {
    id: number;
    title: string;
    description: string;
    author: string;
    version: string;
    status: string;
    priority: Priority;
  }

  const sortByField = (item1: Issue, item2: Issue) => {
    const result =
      item1[router.query.orderBy as keyof Issue] <
      item2[router.query.orderBy as keyof Issue]
        ? 1
        : -1;
    if (router.query.order === "asc") return result * -1;
    return result;
  };

  useEffect(() => {
    console.log(rows.sort(sortByField));
  }, [router]);

  const rows: Array<Issue> = [
    {
      id: 1,
      title: "Teste1",
      description: "Teste",
      author: "Fulano",
      version: "1.0",
      status: "NOVO",
      priority: Priority["BAIXA"],
    },
    {
      id: 2,
      title: "Teste2",
      description: "Teste2",
      author: "Fulano2",
      version: "2.0",
      status: "APROVADO",
      priority: "NORMAL",
    },
    {
      id: 3,
      title: "Teste3",
      description: "Teste3",
      author: "Fulano3",
      version: "3.0",
      status: "APROVADO",
      priority: "ALTA",
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <TableContainer component={Paper}>
          <Table>
            <TableHeadEnhanced />
            <TableBody>
              {rows.sort(sortByField).map((row) => (
                <TableRow key={row.id}>
                  <TableCell>{row.id}</TableCell>
                  <TableCell>{row.title}</TableCell>
                  <TableCell>{row.description}</TableCell>
                  <TableCell>{row.author}</TableCell>
                  <TableCell>{row.version}</TableCell>
                  <TableCell>{row.status}</TableCell>
                  <TableCell>{row.priority}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Container>
    </div>
  );
};

export default Home;
